version: '3'

services:
  web:
    build: ./web
    command: gunicorn dobriybober.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/dobriybober
    expose:
      - 8000
    networks:
      - app
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0.29
    ports:
      - '3331:3306'
    environment:
      MYSQL_DATABASE: 'bobje'
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    networks:
      - app

  nginx:
    build: ./web/nginx
    volumes:
      - .:/dobriybober
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - app

networks:
  app:
    driver: bridge